/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.print.PageFormat;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static project.things4.PASS;
import static project.things4.PATH;
import static project.things4.PLACE;
import static project.things4.UNAME;

/**
 *
 * @author hp
 */
public class fees extends javax.swing.JInternalFrame {
    public static String ab;
    // * Creates new form fee
    // */
    public fees() {
        initComponents();
        jButton10.setEnabled(false);jButton12.setEnabled(false);
        
        Date obj1=new Date();
        pdatebox.setDate(obj1);
        
        
         try{
        Connection myconnection;
               myconnection=DriverManager.getConnection(PATH+PLACE,UNAME,PASS);
        try
        {
            String a="Select * from classtable";
            PreparedStatement mystatement= myconnection.prepareStatement(a);
            ResultSet myresult=mystatement.executeQuery();
            if(myresult.next())
            {
                do{
                    
                    classbox.addItem(myresult.getString("class"));
                  
                    
                }
                while(myresult.next());
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "Query Error due to " + e.getMessage());
        }
        finally
        {
            myconnection.close();
        } } catch (SQLException ex) {
               Logger.getLogger(misc.class.getName()).log(Level.SEVERE, null, ex);
        }           
 
        
        
         try{
        Connection myconnection;
               myconnection=DriverManager.getConnection(PATH+PLACE,UNAME,PASS);
        try
        {
            String a="Select * from sectiontable";
            PreparedStatement mystatement= myconnection.prepareStatement(a);
            ResultSet myresult=mystatement.executeQuery();
            if(myresult.next())
            {
                do{
                    sectionbox.addItem(myresult.getString("section"));
                }
                while(myresult.next());
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "Query Error due to " + e.getMessage());
        }
        finally
        {
            myconnection.close();
        } } catch (SQLException ex) {
               Logger.getLogger(misc.class.getName()).log(Level.SEVERE, null, ex);
        }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSplitPane1 = new javax.swing.JSplitPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        adbox = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        father = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        mother = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        phone = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        landline = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        tfbox = new javax.swing.JFormattedTextField();
        jLabel33 = new javax.swing.JLabel();
        termbox = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        pdatebox = new com.toedter.calendar.JDateChooser();
        jLabel35 = new javax.swing.JLabel();
        cheque = new javax.swing.JRadioButton();
        cash = new javax.swing.JRadioButton();
        jLabel36 = new javax.swing.JLabel();
        due = new javax.swing.JLabel();
        classbox = new javax.swing.JComboBox<>();
        sectionbox = new javax.swing.JComboBox<>();
        paidbox = new javax.swing.JFormattedTextField();
        jButton12 = new javax.swing.JButton();
        nbtn = new javax.swing.JRadioButton();
        adbtn = new javax.swing.JRadioButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setIconifiable(true);
        setTitle("Fees Management");
        setPreferredSize(new java.awt.Dimension(1026, 569));

        jLabel28.setText("Search by");

        jButton9.setText("Search");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel29.setText("Father's Name");

        jLabel30.setText("Mother's Name");

        jLabel31.setText("Class");

        jLabel32.setText("Section ");

        jButton10.setText("Update");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel16.setText("Phone Number");

        phone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel17.setText("Landline Number");

        landline.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel11.setText("Total Fees");

        tfbox.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel33.setText("Paid");

        termbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Term", "1st Term", "2nd Term" }));

        jLabel34.setText("Paid Date");

        jLabel35.setText("Mode Of Payment");

        buttonGroup1.add(cheque);
        cheque.setText("Cheque");

        buttonGroup1.add(cash);
        cash.setText("Cash");

        jLabel36.setText("Due Amount");

        due.setText("0");
        due.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                dueMouseMoved(evt);
            }
        });

        classbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Class" }));
        classbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classbox2ActionPerformed(evt);
            }
        });

        sectionbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Section" }));
        sectionbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sectionboxActionPerformed(evt);
            }
        });

        paidbox.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        paidbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paidboxMouseExited(evt);
            }
        });
        paidbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paidboxActionPerformed(evt);
            }
        });

        jButton12.setText("Print Receipt");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        buttonGroup2.add(nbtn);
        nbtn.setText("Name");

        buttonGroup2.add(adbtn);
        adbtn.setText("Admission Number");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(adbox, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton9)
                        .addGap(683, 683, 683))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel31))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(classbox, 0, 150, Short.MAX_VALUE)
                                    .addComponent(father))
                                .addGap(211, 211, 211)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel32)
                                    .addComponent(jLabel17))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(mother, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(sectionbox, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(landline, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel33)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel34))
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(tfbox, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                            .addGap(19, 19, 19)
                                            .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cheque)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cash))
                                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                                    .addGap(18, 18, 18)
                                                    .addComponent(pdatebox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                                    .addGap(19, 19, 19)
                                                    .addComponent(termbox, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(18, 18, 18)
                                        .addComponent(paidbox, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel35)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton10)
                                    .addComponent(jLabel36))
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton12))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(67, 67, 67)
                                        .addComponent(due, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addGap(18, 18, 18)
                                .addComponent(nbtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(adbtn)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nbtn)
                    .addComponent(adbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(father)
                        .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mother))
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel32)
                        .addComponent(classbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sectionbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(landline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(termbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paidbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pdatebox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(cheque)
                    .addComponent(cash))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(due))
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(jButton12))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paidboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paidboxActionPerformed
        int d,b,c;
        d=Integer.parseInt(tfbox.getText());
        b=Integer.parseInt(paidbox.getText());
        c=d-b;
        due.setText(String.valueOf(c));
    }//GEN-LAST:event_paidboxActionPerformed

    private void sectionboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sectionboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sectionboxActionPerformed

    private void classbox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classbox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classbox2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try
        {
            Connection myconnection;

            myconnection=DriverManager.getConnection(PATH+PLACE,UNAME,PASS);

            try
            {
                String a="insert into feetable values(?,?,?,?,?,?,?)";
                PreparedStatement mystatement=myconnection.prepareStatement(a);
                mystatement.setString(1, adbox.getText());
                mystatement.setString(2, tfbox.getText());
                mystatement.setString(3, paidbox.getText());
                mystatement.setString(7, due.getText());
                mystatement.setString(4, termbox.getSelectedItem().toString());

                SimpleDateFormat myformat=new SimpleDateFormat("yyyy-MM-dd");
                mystatement.setString(5, myformat.format(pdatebox.getDate()));
                if(cheque.isSelected())
                {
                    mystatement.setString(6, "cheque");
                }
                else if(cash.isSelected())
                {
                    mystatement.setString(6, "cash");
                }

                if(mystatement.executeUpdate()>0)
                {
                    jButton12.setEnabled(true);
                    tfbox.setText("");
                    paidbox.setText("");
                    due.setText("");
                    termbox.setSelectedIndex(0);
                    JOptionPane.showMessageDialog(rootPane, "Fee Data Saved Successfully");
                }

            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane, "Fill All Fields");
            }
            finally
            {
                myconnection.close();
            }

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
if(adbtn.isSelected()){ try
{
Connection myconnection;

myconnection=DriverManager.getConnection(PATH+PLACE,UNAME,PASS);

try
{
String a="select * from studenttable where admno=?";
PreparedStatement mystatement=myconnection.prepareStatement(a);
mystatement.setString(1, adbox.getText());
ResultSet myresult=mystatement.executeQuery();
if(myresult.next())
{
    ab=myresult.getString("admno");
     father.setText(myresult.getString("fname"));
     mother.setText(myresult.getString("lname"));
     
     
     classbox.setSelectedItem(myresult.getString("class"));
     sectionbox.setSelectedItem(myresult.getString("section"));
     phone.setText(myresult.getString("phone"));
     
     landline.setText(myresult.getString("landline"));
     jButton10.setEnabled(true);
}
else{JOptionPane.showMessageDialog(rootPane, "Admission No Not Found");}

}
catch(Exception e)
{
JOptionPane.showMessageDialog(rootPane, "Error in Query " + e.getMessage());
}
finally
{
myconnection.close();
}


}
catch(Exception e)
{
JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
}
       }
       
       
       if(nbtn.isSelected()){ try
{
Connection myconnection;

myconnection=DriverManager.getConnection(PATH+PLACE,UNAME,PASS);

try
{
String a="select * from studenttable where fname=?";
PreparedStatement mystatement=myconnection.prepareStatement(a);
mystatement.setString(1, adbox.getText());
ResultSet myresult=mystatement.executeQuery();
if(myresult.next())
{
     father.setText(myresult.getString("fname"));
     mother.setText(myresult.getString("lname"));
     
     
     classbox.setSelectedItem(myresult.getString("class"));
     sectionbox.setSelectedItem(myresult.getString("section"));
     phone.setText(myresult.getString("phone"));
     
     landline.setText(myresult.getString("landline"));
     jButton10.setEnabled(true);
}
else{JOptionPane.showMessageDialog(rootPane, "Name not Found");}

}
catch(Exception e)
{
JOptionPane.showMessageDialog(rootPane, "Error in Query " + e.getMessage());
}
finally
{
myconnection.close();
}


}
catch(Exception e)
{
JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
}
       }
 
    }//GEN-LAST:event_jButton9ActionPerformed

    private void paidboxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paidboxMouseExited
      int d,b,c;
        d=Integer.parseInt(tfbox.getText());
        b=Integer.parseInt(paidbox.getText());
        c=d-b;
        due.setText(String.valueOf(c));
    }//GEN-LAST:event_paidboxMouseExited

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
feereceipt obj=new feereceipt();
Parentframe.dp.add(obj);
obj.setVisible(true);
 PrinterJob job = PrinterJob.getPrinterJob();
job.setPrintable(obj);
PageFormat myformat=job.defaultPage();
myformat.setOrientation(PageFormat.LANDSCAPE);
PageFormat postformat = job.pageDialog(myformat);
if (myformat != postformat) {
boolean ok = job.printDialog();
if (ok) 
{
try {

job.print();

} catch (PrinterException ex) {
JOptionPane.showMessageDialog(null, "The job did not successfully complete");
}
}
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void dueMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dueMouseMoved
      int d,b,c;
        d=Integer.parseInt(tfbox.getText());
        b=Integer.parseInt(paidbox.getText());
        c=d-b;
        due.setText(String.valueOf(c));
    }//GEN-LAST:event_dueMouseMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adbox;
    private javax.swing.JRadioButton adbtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton cash;
    private javax.swing.JRadioButton cheque;
    private javax.swing.JComboBox<String> classbox;
    private javax.swing.JLabel due;
    private javax.swing.JTextField father;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JFormattedTextField landline;
    private javax.swing.JTextField mother;
    private javax.swing.JRadioButton nbtn;
    private javax.swing.JFormattedTextField paidbox;
    private com.toedter.calendar.JDateChooser pdatebox;
    private javax.swing.JFormattedTextField phone;
    private javax.swing.JComboBox<String> sectionbox;
    private javax.swing.JComboBox<String> termbox;
    private javax.swing.JFormattedTextField tfbox;
    // End of variables declaration//GEN-END:variables
}
